Repository sonia-auv/provider_thruster, pull requests merged in 2020-07, with the labels that each got.

#13 Feature/dockerize repo
  .devcontainer/devcontainer.json
  .github/workflows/docker-image-robot-develop.yml
  .github/workflows/docker-image-robot-feature.yml
  .github/workflows/docker-image-robot-master.yml
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/tasks.json
  Dockerfile
  LICENSE
  README.md
  scripts/sonia_entrypoint.sh
Labels: Priority: High, Type: Feature

#15 Fix test
  .dockerignore
  .github/workflows/docker-image-perception-develop.yml
  .github/workflows/docker-image-perception-feature.yml
  .github/workflows/docker-image-perception-master.yml
  CMakeLists.txt
  Dockerfile
  package.xml
  src/provider_thruster/provider_thruster_node.cc
  src/provider_thruster/provider_thruster_node.h
  test/provider_thruster_test.cc
Labels: Priority: Medium, Type: Bug

#17 Removing tests
  test/CMakeLists.txt
  test/provider_thruster_test.cc
Labels: Priority: High

#18 Fix cmake
  CMakeLists.txt
Labels: Priority: High
